package fairygui.editor.utils
{
   public class RuntimeErrorUtil_ERROR_DATA
   {
      
      public static var data:XML = <runtimeErrors>
  <error id="1024"><![CDATA[RuntimeError #1024: Stack underflow.]]></error>
  <error id="1025"><![CDATA[RuntimeError #1025: An invalid register %d was accessed.]]></error>
  <error id="1026"><![CDATA[RuntimeError #1026: Slot %d exceeds slotCount=%d of %t.]]></error>
  <error id="1027"><![CDATA[RuntimeError #1027: Method_info %d exceeds method_count=%d.]]></error>
  <error id="1028"><![CDATA[RuntimeError #1028: Disp_id %d exceeds max_disp_id=%d of %t.]]></error>
  <error id="1029"><![CDATA[RuntimeError #1029: Disp_id %d is undefined on %t.]]></error>
  <error id="1030"><![CDATA[RuntimeError #1030: Stack depth unbalanced.]]></error>
  <error id="1031"><![CDATA[RuntimeError #1031: Scope depth unbalanced.]]></error>
  <error id="1032"><![CDATA[RuntimeError #1032: Cpool index %d out of range %d.]]></error>
  <error id="1033"><![CDATA[RuntimeError #1033: Cpool entry %d wrong type.]]></error>
  <error id="1034"><![CDATA[RuntimeError #1034: Type Coercion failed: cannot convert %a to %t]]></error>
  <error id="1035"><![CDATA[RuntimeError #1035: Illegal super expression in method %m.]]></error>
  <error id="2060"><![CDATA[RuntimeError #2060: Security sandbox violation: ExternalInterface caller %1 cannot access %2.]]></error>
  <error id="1037"><![CDATA[RuntimeError #1037: Cannot assign to a method %n on %t.]]></error>
  <error id="1038"><![CDATA[RuntimeError #1038: %n is already defined.]]></error>
  <error id="1039"><![CDATA[RuntimeError #1039: Cannot verify method until it is referenced.]]></error>
  <error id="1040"><![CDATA[RuntimeError #1040: RHS of instanceof must be a Class or Function]]></error>
  <error id="1041"><![CDATA[RuntimeError #1041: RHS of operator must be a Class]]></error>
  <error id="1042"><![CDATA[RuntimeError #1042: Not an ABC file.]]></error>
  <error id="1043"><![CDATA[RuntimeError #1043: Invalid code_length=%d.]]></error>
  <error id="1044"><![CDATA[RuntimeError #1044: MethodInfo-%d unsupported flags=%d.]]></error>
  <error id="1045"><![CDATA[RuntimeError #1045: Unsupported traits kind=%d.]]></error>
  <error id="1046"><![CDATA[RuntimeError #1046: MethodInfo-%d referenced before definition.]]></error>
  <error id="1047"><![CDATA[RuntimeError #1047: No Entry Point Found.]]></error>
  <error id="2055"><![CDATA[RuntimeError #2055: The print job could not be started.]]></error>
  <error id="1049"><![CDATA[RuntimeError #1049: Prototype objects must be vanilla Objects.]]></error>
  <error id="1050"><![CDATA[RuntimeError #1050: Cannot convert %o to primitive.]]></error>
  <error id="1051"><![CDATA[RuntimeError #1051: Illegal early binding access to %t.]]></error>
  <error id="1052"><![CDATA[RuntimeError #1052: Invalid URI passed to %s function.]]></error>
  <error id="1053"><![CDATA[RuntimeError #1053: Illegal override of %n in %t.]]></error>
  <error id="1054"><![CDATA[RuntimeError #1054: Illegal range or target offsets in exception handler.]]></error>
  <error id="1055"><![CDATA[RuntimeError #1055: %S has no properties]]></error>
  <error id="1056"><![CDATA[RuntimeError #1056: Cannot create property %n on %t]]></error>
  <error id="1057"><![CDATA[RuntimeError #1057: %t may only contain methods.]]></error>
  <error id="1058"><![CDATA[RuntimeError #1058: Illegal operand type: %t must be %t.]]></error>
  <error id="1059"><![CDATA[RuntimeError #1059: ClassInfo-%d referenced before definition.]]></error>
  <error id="1060"><![CDATA[RuntimeError #1060: ClassInfo %d exceeds class_count=%d.]]></error>
  <error id="1061"><![CDATA[RuntimeError #1061: The value %1 cannot be converted to %2 without losing precision.]]></error>
  <error id="2048"><![CDATA[RuntimeError #2048: Security sandbox violation: %1 cannot load data from %2.]]></error>
  <error id="1063"><![CDATA[RuntimeError #1063: Argument count mismatch on %m.]]></error>
  <error id="1064"><![CDATA[RuntimeError #1064: Cannot call method %m as constructor]]></error>
  <error id="1065"><![CDATA[RuntimeError #1065: Variable %n is not defined]]></error>
  <error id="1066"><![CDATA[RuntimeError #1066: Function('function body') is not supported]]></error>
  <error id="1067"><![CDATA[RuntimeError #1067: Native method %m has illegal method body.]]></error>
  <error id="1068"><![CDATA[RuntimeError #1068: %t and %t cannot be reconciled.]]></error>
  <error id="1069"><![CDATA[RuntimeError #1069: Property %n not found on %t and there is no default value]]></error>
  <error id="1070"><![CDATA[RuntimeError #1070: Method %n not found on %t]]></error>
  <error id="1071"><![CDATA[RuntimeError #1071: Function %m has already been bound to %t.]]></error>
  <error id="1072"><![CDATA[RuntimeError #1072: Disp_id 0 is illegal.]]></error>
  <error id="1073"><![CDATA[RuntimeError #1073: Non-override method %m replaced because of duplicate disp_id %d.]]></error>
  <error id="2071"><![CDATA[RuntimeError #2071: The Stage class does not implement this property or method.]]></error>
  <error id="1075"><![CDATA[RuntimeError #1075: Math is not a function]]></error>
  <error id="1076"><![CDATA[RuntimeError #1076: Math is not a constructor]]></error>
  <error id="1077"><![CDATA[RuntimeError #1077: Illegal read of write-only property %n on %t]]></error>
  <error id="1078"><![CDATA[RuntimeError #1078: Illegal opcode/multiname combination: %d  &#60;%n&#62;.]]></error>
  <error id="1079"><![CDATA[RuntimeError #1079: Native methods not allowed in loaded code.]]></error>
  <error id="1080"><![CDATA[RuntimeError #1080: Illegal value for namespace.]]></error>
  <error id="2078"><![CDATA[RuntimeError #2078: The name property of a Timeline-placed object cannot be modified.]]></error>
  <error id="1082"><![CDATA[RuntimeError #1082: No default namespace has been set.]]></error>
  <error id="1083"><![CDATA[RuntimeError #1083: The prefix "%S" for element "%w" is not bound.]]></error>
  <error id="1084"><![CDATA[RuntimeError #1084: Element or attribute ("%w") do not match QName production: QName::=(NCName':')?NCName]]></error>
  <error id="1085"><![CDATA[RuntimeError #1085: The element type "%S" must be terminated by the matching end-tag "</%S>".]]></error>
  <error id="1086"><![CDATA[RuntimeError #1086: The %s method works only on lists containing one item.]]></error>
  <error id="1087"><![CDATA[RuntimeError #1087: Assignment to indexed XML is not allowed.]]></error>
  <error id="1088"><![CDATA[RuntimeError #1088: The markup in the document following the root element must be well-formed.]]></error>
  <error id="1089"><![CDATA[RuntimeError #1089: Assignment to lists with more than one item is not supported]]></error>
  <error id="1090"><![CDATA[RuntimeError #1090: XML parser failure: element is malformed]]></error>
  <error id="1091"><![CDATA[RuntimeError #1091: XML parser failure: Unterminated CDATA section]]></error>
  <error id="1092"><![CDATA[RuntimeError #1092: XML parser failure: Unterminated XML declaration]]></error>
  <error id="1093"><![CDATA[RuntimeError #1093: XML parser failure: Unterminated DOCTYPE declaration]]></error>
  <error id="1094"><![CDATA[RuntimeError #1094: XML parser failure: Unterminated comment]]></error>
  <error id="1095"><![CDATA[RuntimeError #1095: XML parser failure: Unterminated attribute]]></error>
  <error id="1096"><![CDATA[RuntimeError #1096: XML parser failure: Unterminated element]]></error>
  <error id="1097"><![CDATA[RuntimeError #1097: XML parser failure: Unterminated processing instruction]]></error>
  <error id="1098"><![CDATA[RuntimeError #1098: Illegal prefix '%S' for 'no namespace'.]]></error>
  <error id="2073"><![CDATA[RuntimeError #2073: There was a problem saving the application to disk.]]></error>
  <error id="1100"><![CDATA[RuntimeError #1100: Cannot supply flags when constructing one RegExp from another.]]></error>
  <error id="1101"><![CDATA[RuntimeError #1101: Cannot verify method %m with unknown scope.]]></error>
  <error id="1102"><![CDATA[RuntimeError #1102: Illegal default value for type %n.]]></error>
  <error id="1103"><![CDATA[RuntimeError #1103: Class %n cannot extend final base class.]]></error>
  <error id="1104"><![CDATA[RuntimeError #1104: Attribute "%S" was already specified for element "%S".]]></error>
  <error id="2066"><![CDATA[RuntimeError #2066: The Timer delay specified is out of range.]]></error>
  <error id="2053"><![CDATA[RuntimeError #2053: Security sandbox violation: %1 cannot clear an interval timer set by %2.]]></error>
  <error id="1107"><![CDATA[RuntimeError #1107: The ABC data is corrupt, attempt to read out of bounds.]]></error>
  <error id="1108"><![CDATA[RuntimeError #1108: The OP_newclass opcode was used with the incorrect base class.]]></error>
  <error id="1109"><![CDATA[RuntimeError #1109: Attempt to directly call unbound function %m from method %m.]]></error>
  <error id="1110"><![CDATA[RuntimeError #1110: %n cannot extend %t.]]></error>
  <error id="1111"><![CDATA[RuntimeError #1111: %n cannot implement %t.]]></error>
  <error id="1112"><![CDATA[RuntimeError #1112: Argument count mismatch on class coercion.]]></error>
  <error id="1113"><![CDATA[RuntimeError #1113: OP_newactivation used in method without NEED_ACTIVATION flag.]]></error>
  <error id="1114"><![CDATA[RuntimeError #1114: OP_getglobalslot or OP_setglobalslot used with no global scope.]]></error>
  <error id="1115"><![CDATA[RuntimeError #1115: %n is not a constructor]]></error>
  <error id="1116"><![CDATA[RuntimeError #1116: second argument to Function.prototype.apply must be an array]]></error>
  <error id="2049"><![CDATA[RuntimeError #2049: Security sandbox violation: %1 cannot upload data to %2.]]></error>
  <error id="2065"><![CDATA[RuntimeError #2065: The focus cannot be set for this target.]]></error>
  <error id="2051"><![CDATA[RuntimeError #2051: Security sandbox violation: %1 cannot evaluate scripting URLs within %2 (allowScriptAccess is %3).]]></error>
  <error id="2052"><![CDATA[RuntimeError #2052: Only String arguments are permitted for allowDomain and allowInsecureDomain.]]></error>
  <error id="2095"><![CDATA[RuntimeError #2095: %1 was unable to invoke callback %2.]]></error>
  <error id="2054"><![CDATA[RuntimeError #2054: The value of Security.exactSettings cannot be changed after it has been used.]]></error>
  <error id="2070"><![CDATA[RuntimeError #2070: Security sandbox violation: caller %1 cannot access Stage owned by %2.]]></error>
  <error id="2056"><![CDATA[RuntimeError #2056: The print job could not be sent to the printer.]]></error>
  <error id="2057"><![CDATA[RuntimeError #2057: The page could not be added to the print job.]]></error>
  <error id="2087"><![CDATA[RuntimeError #2087: The FileReference.download() file name contains prohibited characters.]]></error>
  <error id="2074"><![CDATA[RuntimeError #2074: The stage is too small to fit the download ui.]]></error>
  <error id="2075"><![CDATA[RuntimeError #2075: The downloaded file is invalid.]]></error>
  <error id="2061"><![CDATA[RuntimeError #2061: No ExternalInterface callback %1 registered.]]></error>
  <error id="2062"><![CDATA[RuntimeError #2062: Children of Event must override clone() {return new MyEventClass (...);}.]]></error>
  <error id="2063"><![CDATA[RuntimeError #2063: Error attempting to execute IME command.]]></error>
  <error id="2079"><![CDATA[RuntimeError #2079: Classes derived from Bitmap can only be associated with defineBits characters (bitmaps).]]></error>
  <error id="2094"><![CDATA[RuntimeError #2094: Event dispatch recursion overflow.]]></error>
  <error id="2108"><![CDATA[RuntimeError #2108: Scene %1 was not found.]]></error>
  <error id="2082"><![CDATA[RuntimeError #2082: Connect failed because the object is already connected.]]></error>
  <error id="2068"><![CDATA[RuntimeError #2068: Invalid sound.]]></error>
  <error id="2069"><![CDATA[RuntimeError #2069: The Loader class does not implement this method.]]></error>
  <error id="2099"><![CDATA[RuntimeError #2099: The loading object is not sufficiently loaded to provide this information.]]></error>
  <error id="2086"><![CDATA[RuntimeError #2086: A setting in the mms.cfg file prohibits this FileReference request.]]></error>
  <error id="2101"><![CDATA[RuntimeError #2101: The String passed to URLVariables.decode() must be a URL-encoded query string containing name/value pairs.]]></error>
  <error id="2102"><![CDATA[RuntimeError #2102: The before XMLNode parameter must be a child of the caller.]]></error>
  <error id="2103"><![CDATA[RuntimeError #2103: XML recursion failure: new child would create infinite loop.]]></error>
  <error id="2059"><![CDATA[RuntimeError #2059: Security sandbox violation: %1 cannot overwrite an ExternalInterface callback added by %2.]]></error>
  <error id="2118"><![CDATA[RuntimeError #2118: The LoaderInfo class does not implement this method.]]></error>
  <error id="2077"><![CDATA[RuntimeError #2077: This filter operation cannot be performed with the specified input parameters.]]></error>
  <error id="2143"><![CDATA[RuntimeError #2143: AccessibilityImplementation.get_accRole() must be overridden from its default.]]></error>
  <error id="2121"><![CDATA[RuntimeError #2121: Security sandbox violation: %1: %2 cannot access %3.]]></error>
  <error id="2109"><![CDATA[RuntimeError #2109: Frame label %1 not found in scene %2.]]></error>
  <error id="2096"><![CDATA[RuntimeError #2096: The HTTP request header %1 cannot be set via ActionScript.]]></error>
  <error id="2097"><![CDATA[RuntimeError #2097: The FileFilter Array is not in the correct format.]]></error>
  <error id="2083"><![CDATA[RuntimeError #2083: Close failed because the object is not connected.]]></error>
  <error id="2084"><![CDATA[RuntimeError #2084: The AMF encoding of the arguments cannot exceed 40K.]]></error>
  <error id="2100"><![CDATA[RuntimeError #2100: The ByteArray parameter in Loader.loadBytes() must have length greater than 0.]]></error>
  <error id="2140"><![CDATA[RuntimeError #2140: Security sandbox violation: %1 cannot load %2.]]></error>
  <error id="2116"><![CDATA[RuntimeError #2116: Parameter %1 must be true.]]></error>
  <error id="2142"><![CDATA[RuntimeError #2142: Security sandbox violation: local SWF files cannot use the LoaderContext.securityDomain property.]]></error>
  <error id="2131"><![CDATA[RuntimeError #2131: Definition %1 cannot be found.]]></error>
  <error id="2119"><![CDATA[RuntimeError #2119: Security sandbox violation: caller %1 cannot access LoaderInfo.applicationDomain owned by %2.]]></error>
  <error id="2133"><![CDATA[RuntimeError #2133: Callback %1 is not registered.]]></error>
  <error id="2134"><![CDATA[RuntimeError #2134: Cannot create SharedObject.]]></error>
  <error id="2122"><![CDATA[RuntimeError #2122: Security sandbox violation: %1: %2 cannot access %3.]]></error>
  <error id="2123"><![CDATA[RuntimeError #2123: Security sandbox violation: %1: %2 cannot access %3.]]></error>
  <error id="2110"><![CDATA[RuntimeError #2110: The value of Security.disableAVM1Loading cannot be set unless the caller can access the stage and is in an ActionScript 3.0 SWF file.]]></error>
  <error id="2111"><![CDATA[RuntimeError #2111: Security.disableAVM1Loading is true so the current load of the ActionScript 1.0/2.0 SWF file has been blocked.]]></error>
  <error id="2112"><![CDATA[RuntimeError #2112: Provided parameter LoaderContext.ApplicationDomain is from a disallowed domain.]]></error>
  <error id="2098"><![CDATA[RuntimeError #2098: The loading object is not a .swf file, you cannot request SWF properties from it.]]></error>
  <error id="2141"><![CDATA[RuntimeError #2141: Only one PrintJob may be in use at a time.]]></error>
  <error id="2067"><![CDATA[RuntimeError #2067: The ExternalInterface is not available in this container.]]></error>
  <error id="2155"><![CDATA[RuntimeError #2155: The ExternalInterface.call functionName parameter is invalid.]]></error>
  <error id="2156"><![CDATA[RuntimeError #2156: Port %1 may not be accessed using protocol %2.]]></error>
  <error id="2132"><![CDATA[RuntimeError #2132: NetConnection.connect cannot be called from a netStatus event handler.]]></error>
  <error id="2158"><![CDATA[RuntimeError #2158: The NetConnection Object is invalid.]]></error>
  <error id="2159"><![CDATA[RuntimeError #2159: The SharedObject Object is invalid.]]></error>
  <error id="2148"><![CDATA[RuntimeError #2148: SWF file %1 cannot access local resource %2.]]></error>
  <error id="2136"><![CDATA[RuntimeError #2136: The SWF file %1 contains invalid data.]]></error>
  <error id="2137"><![CDATA[RuntimeError #2137: Security sandbox violation: %1 cannot navigate window %2 within %3 (allowScriptAccess is %4).]]></error>
  <error id="2138"><![CDATA[RuntimeError #2138: Rich text XML could not be parsed.]]></error>
  <error id="2125"><![CDATA[RuntimeError #2125: Security sandbox violation: %1 cannot use Runtime Shared Library %2 because crossing the boundary between ActionScript 3.0 and ActionScript 1.0/2.0 objects is not allowed.]]></error>
  <error id="2126"><![CDATA[RuntimeError #2126: NetConnection object must be connected.]]></error>
  <error id="2127"><![CDATA[RuntimeError #2127: FileReference POST data cannot be type ByteArray.]]></error>
  <error id="2113"><![CDATA[RuntimeError #2113: Provided parameter LoaderContext.SecurityDomain is from a disallowed domain.]]></error>
  <error id="2129"><![CDATA[RuntimeError #2129: Connection to %1 failed.]]></error>
  <error id="2115"><![CDATA[RuntimeError #2115: Parameter %1 must be false.]]></error>
  <error id="2145"><![CDATA[RuntimeError #2145: Cumulative length of requestHeaders must be less than 8192 characters.]]></error>
  <error id="2171"><![CDATA[RuntimeError #2171: The Shader object contains no byte code to execute.]]></error>
  <error id="2172"><![CDATA[RuntimeError #2172: The ShaderJob is already running or finished.]]></error>
  <error id="2161"><![CDATA[RuntimeError #2161: An internal error occured while laying out the text.]]></error>
  <error id="2149"><![CDATA[RuntimeError #2149: Security sandbox violation: %1 cannot make fscommand calls to %2 (allowScriptAccess is %3).]]></error>
  <error id="2150"><![CDATA[RuntimeError #2150: An object cannot be added as a child to one of it's children (or children's children, etc.).]]></error>
  <error id="2151"><![CDATA[RuntimeError #2151: You cannot enter full screen mode when the settings dialog is visible.]]></error>
  <error id="2152"><![CDATA[RuntimeError #2152: Full screen mode is not allowed.]]></error>
  <error id="2153"><![CDATA[RuntimeError #2153: The URLRequest.requestHeaders array must contain only non-NULL URLRequestHeader objects.]]></error>
  <error id="2167"><![CDATA[RuntimeError #2167: The Shader does not have the required number of inputs for this operation.]]></error>
  <error id="2168"><![CDATA[RuntimeError #2168: Static text lines have no atoms and no reference to a text block.]]></error>
  <error id="2169"><![CDATA[RuntimeError #2169: The method %1 may not be used for browser scripting.]]></error>
  <error id="2157"><![CDATA[RuntimeError #2157: Rejecting URL %1 because the 'asfunction:' protocol may only be used for link targets, not for networking APIs.]]></error>
  <error id="2144"><![CDATA[RuntimeError #2144: AccessibilityImplementation.get_accState() must be overridden from its default.]]></error>
  <error id="2114"><![CDATA[RuntimeError #2114: Parameter %1 must be null.]]></error>
  <error id="2160"><![CDATA[RuntimeError #2160: The TextLine is INVALID and cannot be used to access the current state of the TextBlock.]]></error>
  <error id="2186"><![CDATA[RuntimeError #2186: Invalid focalLength %1.]]></error>
  <error id="2187"><![CDATA[RuntimeError #2187: Invalid orientation style %1.]]></error>
  <error id="2188"><![CDATA[RuntimeError #2188: Invalid raw matrix.]]></error>
  <error id="2164"><![CDATA[RuntimeError #2164: The Shader input %1 is missing or an unsupported type.]]></error>
  <error id="2165"><![CDATA[RuntimeError #2165: The Shader input %1 does not have enough data.]]></error>
  <error id="2166"><![CDATA[RuntimeError #2166: The Shader input %1 lacks valid dimensions.]]></error>
  <error id="2180"><![CDATA[RuntimeError #2180: It is illegal to move AVM1 content (AS1 or AS2) to a different part of the displayList when it has been loaded into AVM2 (AS3) content.]]></error>
  <error id="2139"><![CDATA[RuntimeError #2139: SharedObject could not connect.]]></error>
  <error id="2124"><![CDATA[RuntimeError #2124: Loaded file is an unknown type.]]></error>
  <error id="2183"><![CDATA[RuntimeError #2183: Scale values must not be zero.]]></error>
  <error id="2184"><![CDATA[RuntimeError #2184: The ElementFormat object is locked and cannot be modified.]]></error>
  <error id="3116"><![CDATA[RuntimeError #3116: An internal logic error occurred.]]></error>
  <error id="3117"><![CDATA[RuntimeError #3117: Access permission denied.]]></error>
  <error id="2174"><![CDATA[RuntimeError #2174: Only one download, upload, load or save operation can be active at a time on each FileReference.]]></error>
  <error id="2146"><![CDATA[RuntimeError #2146: Security sandbox violation: %1 cannot call %2 because the HTML/container parameter allowNetworking has the value %3.]]></error>
  <error id="2201"><![CDATA[RuntimeError #2201: The requested update type is not supported on this operating system.]]></error>
  <error id="2163"><![CDATA[RuntimeError #2163: The Shader input type %1 is not compatible for this operation.]]></error>
  <error id="2203"><![CDATA[RuntimeError #2203: The requested SystemUpdater action cannot be completed.]]></error>
  <error id="2192"><![CDATA[RuntimeError #2192: An unpaired Unicode surrogate was encountered in the input.]]></error>
  <error id="2205"><![CDATA[RuntimeError #2205: Invalid update type %1.]]></error>
  <error id="2181"><![CDATA[RuntimeError #2181: The TextLine class does not implement this property or method.]]></error>
  <error id="2182"><![CDATA[RuntimeError #2182: Invalid fieldOfView value.]]></error>
  <error id="2154"><![CDATA[RuntimeError #2154: The NetStream Object is invalid.]]></error>
  <error id="2170"><![CDATA[RuntimeError #2170: Security sandbox violation: %1 cannot send HTTP headers to %2.]]></error>
  <error id="2185"><![CDATA[RuntimeError #2185: The FontDescription object is locked and cannot be modified.]]></error>
  <error id="3111"><![CDATA[RuntimeError #3111: An invalid schema type was specified.]]></error>
  <error id="3112"><![CDATA[RuntimeError #3112: An invalid transaction lock type was specified.]]></error>
  <error id="3132"><![CDATA[RuntimeError #3132: Data type mismatch.]]></error>
  <error id="2175"><![CDATA[RuntimeError #2175: One or more elements of the content of the TextBlock has a null ElementFormat.]]></error>
  <error id="2176"><![CDATA[RuntimeError #2176: Certain actions, such as those that display a pop-up window, may only be invoked upon user interaction, for example by a mouse click or button press.]]></error>
  <error id="2162"><![CDATA[RuntimeError #2162: The Shader output type is not compatible for this operation.]]></error>
  <error id="2130"><![CDATA[RuntimeError #2130: Unable to flush SharedObject.]]></error>
  <error id="2179"><![CDATA[RuntimeError #2179: The Clipboard.generalClipboard object may only be read while processing a flash.events.Event.PASTE event.]]></error>
  <error id="3119"><![CDATA[RuntimeError #3119: Database file is currently locked.]]></error>
  <error id="3120"><![CDATA[RuntimeError #3120: Table is locked.]]></error>
  <error id="2196"><![CDATA[RuntimeError #2196: Parameter %1 must be an Object with only String values.]]></error>
  <error id="3141"><![CDATA[RuntimeError #3141: The requested database configuration is not supported.]]></error>
  <error id="3103"><![CDATA[RuntimeError #3103: Operation cannot be performed while there is an open transaction on this connection.]]></error>
  <error id="3104"><![CDATA[RuntimeError #3104: A SQLConnection must be open to perform this operation.]]></error>
  <error id="2200"><![CDATA[RuntimeError #2200: The SystemUpdater class is not supported by this player.]]></error>
  <error id="3106"><![CDATA[RuntimeError #3106: Property cannot be changed while SQLStatement.executing is true.]]></error>
  <error id="2202"><![CDATA[RuntimeError #2202: Only one SystemUpdater action is allowed at a time.]]></error>
  <error id="2189"><![CDATA[RuntimeError #2189: A Matrix3D can not be assigned to more than one DisplayObject.]]></error>
  <error id="2190"><![CDATA[RuntimeError #2190: The attempted load of %1 failed as it had a Content-Disposition of attachment set.]]></error>
  <error id="2191"><![CDATA[RuntimeError #2191: The Clipboard.generalClipboard object may only be written to as the result of user interaction, for example by a mouse click or button press.]]></error>
  <error id="2177"><![CDATA[RuntimeError #2177: The Shader input %1 is too large.]]></error>
  <error id="2178"><![CDATA[RuntimeError #2178: The Clipboard.generalClipboard object must be used instead of creating a new Clipboard.]]></error>
  <error id="2194"><![CDATA[RuntimeError #2194: Parameter %1 cannot be a Loader.]]></error>
  <error id="2147"><![CDATA[RuntimeError #2147: Forbidden protocol in URL %1.]]></error>
  <error id="3115"><![CDATA[RuntimeError #3115: SQL Error.]]></error>
  <error id="3136"><![CDATA[RuntimeError #3136: Auxiliary database format error.]]></error>
  <error id="3137"><![CDATA[RuntimeError #3137: An index specified for a parameter was out of range.]]></error>
  <error id="3138"><![CDATA[RuntimeError #3138: File opened is not a database file.]]></error>
  <error id="3139"><![CDATA[RuntimeError #3139: The page size specified was not valid for this operation.]]></error>
  <error id="3140"><![CDATA[RuntimeError #3140: The encryption key size specified was not valid for this operation.]]></error>
  <error id="3121"><![CDATA[RuntimeError #3121: Out of memory.]]></error>
  <error id="3122"><![CDATA[RuntimeError #3122: Attempt to write a readonly database.]]></error>
  <error id="2204"><![CDATA[RuntimeError #2204: This operation cannot be canceled because it is waiting for user interaction.]]></error>
  <error id="3214"><![CDATA[RuntimeError #3214: NativeProcessStartupInfo.executable does not specify a valid executable file.]]></error>
  <error id="3215"><![CDATA[RuntimeError #3215: NativeProcessStartupInfo.workingDirectory does not specify a valid directory.]]></error>
  <error id="3105"><![CDATA[RuntimeError #3105: Operation is only allowed if a connection has an open transaction.]]></error>
  <error id="2193"><![CDATA[RuntimeError #2193: Security sandbox violation: %1: %2 cannot access %3.]]></error>
  <error id="3107"><![CDATA[RuntimeError #3107: %1 may not be called unless SQLResult.complete is false.]]></error>
  <error id="2195"><![CDATA[RuntimeError #2195: Error thrown as Loader called %1.]]></error>
  <error id="3109"><![CDATA[RuntimeError #3109: Operation is not permitted when the SQLStatement.sqlConnection property is not set.]]></error>
  <error id="3110"><![CDATA[RuntimeError #3110: Operation cannot be performed while SQLStatement.executing is true.]]></error>
  <error id="3206"><![CDATA[RuntimeError #3206: Caller %1 cannot set LoaderInfo property %2.]]></error>
  <error id="3133"><![CDATA[RuntimeError #3133: An internal error occurred.]]></error>
  <error id="3134"><![CDATA[RuntimeError #3134: Feature not supported on this operating system.]]></error>
  <error id="3114"><![CDATA[RuntimeError #3114: An invalid open mode was specified.]]></error>
  <error id="3301"><![CDATA[RuntimeError #3301: User authentication failed.]]></error>
  <error id="3227"><![CDATA[RuntimeError #3227: Cannot launch another application from background.]]></error>
  <error id="3212"><![CDATA[RuntimeError #3212: Cannot perform operation on a NativeProcess that is not running.]]></error>
  <error id="3118"><![CDATA[RuntimeError #3118: Operation aborted.]]></error>
  <error id="3305"><![CDATA[RuntimeError #3305: Can't connect to the server.]]></error>
  <error id="3306"><![CDATA[RuntimeError #3306: Client update required (Flash Access server requires new client).]]></error>
  <error id="3216"><![CDATA[RuntimeError #3216: Error while reading data from NativeProcess.standardOutput.]]></error>
  <error id="3143"><![CDATA[RuntimeError #3143: Unencrypted databases may not be reencrypted.]]></error>
  <error id="3201"><![CDATA[RuntimeError #3201: Adobe Reader cannot be found.]]></error>
  <error id="3202"><![CDATA[RuntimeError #3202: Adobe Reader 8.1 or later cannot be found.]]></error>
  <error id="3220"><![CDATA[RuntimeError #3220: Action '%1' not allowed in current security context '%2'.]]></error>
  <error id="3126"><![CDATA[RuntimeError #3126: Database lock protocol error.]]></error>
  <error id="3127"><![CDATA[RuntimeError #3127: Database is empty.]]></error>
  <error id="3128"><![CDATA[RuntimeError #3128: Disk I/O error occurred.]]></error>
  <error id="3129"><![CDATA[RuntimeError #3129: The database schema changed.]]></error>
  <error id="3108"><![CDATA[RuntimeError #3108: Operation is not permitted when the SQLStatement.text property is not set.]]></error>
  <error id="3131"><![CDATA[RuntimeError #3131: Abort due to constraint violation.]]></error>
  <error id="3308"><![CDATA[RuntimeError #3308: Wrong voucher key.]]></error>
  <error id="3228"><![CDATA[RuntimeError #3228: StageWebView encountered an error during the load operation.]]></error>
  <error id="3320"><![CDATA[RuntimeError #3320: Generic internal Flash Access failure.]]></error>
  <error id="3113"><![CDATA[RuntimeError #3113: Reference specified is not of type File.]]></error>
  <error id="3312"><![CDATA[RuntimeError #3312: Verification of voucher failed.]]></error>
  <error id="3313"><![CDATA[RuntimeError #3313: Write to the file system failed.]]></error>
  <error id="3303"><![CDATA[RuntimeError #3303: Content expired.]]></error>
  <error id="3217"><![CDATA[RuntimeError #3217: Error while reading data from NativeProcess.standardError.]]></error>
  <error id="3218"><![CDATA[RuntimeError #3218: Error while writing data to NativeProcess.standardInput.]]></error>
  <error id="3219"><![CDATA[RuntimeError #3219: The NativeProcess could not be started.]]></error>
  <error id="3318"><![CDATA[RuntimeError #3318: Incompatible version of Flash Access module found.]]></error>
  <error id="3221"><![CDATA[RuntimeError #3221: Adobe Flash Player cannot be found.]]></error>
  <error id="3204"><![CDATA[RuntimeError #3204: An error ocurred trying to load Adobe Reader.]]></error>
  <error id="3100"><![CDATA[RuntimeError #3100: A SQLConnection cannot be closed while statements are still executing.]]></error>
  <error id="3101"><![CDATA[RuntimeError #3101: Database connection is already open.]]></error>
  <error id="3102"><![CDATA[RuntimeError #3102: Name argument specified was invalid.]]></error>
  <error id="3208"><![CDATA[RuntimeError #3208: Attempt to access invalid clipboard.]]></error>
  <error id="3209"><![CDATA[RuntimeError #3209: Attempt to access dead clipboard.]]></error>
  <error id="3210"><![CDATA[RuntimeError #3210: The application attempted to reference a JavaScript object in a HTML page that is no longer loaded.]]></error>
  <error id="3211"><![CDATA[RuntimeError #3211: Drag and Drop File Promise error: %1]]></error>
  <error id="3130"><![CDATA[RuntimeError #3130: Too much data for one row of a table.]]></error>
  <error id="3213"><![CDATA[RuntimeError #3213: Cannot perform operation on a NativeProcess that is already running.]]></error>
  <error id="3307"><![CDATA[RuntimeError #3307: Generic internal Flash Access failure.]]></error>
  <error id="2037"><![CDATA[RuntimeError #2037: Functions called in incorrect sequence, or earlier call was unsuccessful.]]></error>
  <error id="3321"><![CDATA[RuntimeError #3321: Individualization failed.]]></error>
  <error id="3135"><![CDATA[RuntimeError #3135: Authorization denied.]]></error>
  <error id="3323"><![CDATA[RuntimeError #3323: The internal stores are corrupted.]]></error>
  <error id="3200"><![CDATA[RuntimeError #3200: Cannot perform operation on closed window.]]></error>
  <error id="3300"><![CDATA[RuntimeError #3300: Voucher is invalid.]]></error>
  <error id="3314"><![CDATA[RuntimeError #3314: Verification of FLV/F4V header file failed.]]></error>
  <error id="3222"><![CDATA[RuntimeError #3222: The installed version of Adobe Flash Player is too old.]]></error>
  <error id="3223"><![CDATA[RuntimeError #3223: DNS lookup error: platform error %1]]></error>
  <error id="3205"><![CDATA[RuntimeError #3205: Only application-sandbox content can access this feature.]]></error>
  <error id="3225"><![CDATA[RuntimeError #3225: Cannot send data to a location when connected.]]></error>
  <error id="3207"><![CDATA[RuntimeError #3207: Application-sandbox content cannot access this feature.]]></error>
  <error id="3332"><![CDATA[RuntimeError #3332: Cached voucher has expired.]]></error>
  <error id="3123"><![CDATA[RuntimeError #3123: Database disk image is malformed.]]></error>
  <error id="3124"><![CDATA[RuntimeError #3124: Insertion failed because database is full.]]></error>
  <error id="3125"><![CDATA[RuntimeError #3125: Unable to open the database file.]]></error>
  <error id="3311"><![CDATA[RuntimeError #3311: The version of the application does not match the one specified in the DRM policy.]]></error>
  <error id="3325"><![CDATA[RuntimeError #3325: Internal stores are corrupt.]]></error>
  <error id="3326"><![CDATA[RuntimeError #3326: Call customer support.]]></error>
  <error id="3327"><![CDATA[RuntimeError #3327: Clock tampering detected.]]></error>
  <error id="3315"><![CDATA[RuntimeError #3315: The current security context does not allow this operation.]]></error>
  <error id="3302"><![CDATA[RuntimeError #3302: Flash Access server does not support SSL.]]></error>
  <error id="3317"><![CDATA[RuntimeError #3317: Failed to load Flash Access module.]]></error>
  <error id="3304"><![CDATA[RuntimeError #3304: User authorization failed (for example, the user has not purchased the content).]]></error>
  <error id="3319"><![CDATA[RuntimeError #3319: Missing Flash Access module API entry point.]]></error>
  <error id="2036"><![CDATA[RuntimeError #2036: Load Never Completed.]]></error>
  <error id="3334"><![CDATA[RuntimeError #3334: This platform is not allowed to play this content.]]></error>
  <error id="3203"><![CDATA[RuntimeError #3203: Default Adobe Reader must be version 8.1 or later.]]></error>
  <error id="3224"><![CDATA[RuntimeError #3224: Socket message too long]]></error>
  <error id="3310"><![CDATA[RuntimeError #3310: The AIR application or Flash Player SWF does not match the one specified in the DRM policy.]]></error>
  <error id="3226"><![CDATA[RuntimeError #3226: Cannot import a SWF file when LoaderContext.allowCodeImport is false.]]></error>
  <error id="2042"><![CDATA[RuntimeError #2042: The digest property is not supported by this load operation.]]></error>
  <error id="3340"><![CDATA[RuntimeError #3340: Can't play back because connected analog device doesn't have the correct capabilities.]]></error>
  <error id="3229"><![CDATA[RuntimeError #3229: The protocol is not supported.:]]></error>
  <error id="3230"><![CDATA[RuntimeError #3230: The browse operation is unsupported.]]></error>
  <error id="3316"><![CDATA[RuntimeError #3316: The value of LocalConnection.isPerUser cannot be changed because it has already been locked by a call to LocalConnection.connect, .send, or .close.]]></error>
  <error id="2047"><![CDATA[RuntimeError #2047: Security sandbox violation: %1: %2 cannot access %3.]]></error>
  <error id="3345"><![CDATA[RuntimeError #3345: This operation is not permitted with content protected using Flash Access.]]></error>
  <error id="3333"><![CDATA[RuntimeError #3333: The playback window for this policy has expired.]]></error>
  <error id="3347"><![CDATA[RuntimeError #3347: The device does not meet the Flash Access server's playback device constraints.]]></error>
  <error id="3335"><![CDATA[RuntimeError #3335: Invalid version of Flash Access module.]]></error>
  <error id="3322"><![CDATA[RuntimeError #3322: Device binding failed.]]></error>
  <error id="1002"><![CDATA[RuntimeError #1002: The precision argument must be between 0 and 20; got %d.]]></error>
  <error id="3309"><![CDATA[RuntimeError #3309: Video content is corrupted.]]></error>
  <error id="2028"><![CDATA[RuntimeError #2028: Local-with-filesystem SWF file %1 cannot access Internet URL %2.]]></error>
  <error id="3353"><![CDATA[RuntimeError #3353: the server is using an older version of the registration token for this Device Group.]]></error>
  <error id="3341"><![CDATA[RuntimeError #3341: Can't play back on digital device.]]></error>
  <error id="2031"><![CDATA[RuntimeError #2031: Socket Error.]]></error>
  <error id="1008"><![CDATA[RuntimeError #1008: %n is ambiguous; more than one binding matches.]]></error>
  <error id="2033"><![CDATA[RuntimeError #2033: Key Generation Failed.]]></error>
  <error id="2034"><![CDATA[RuntimeError #2034: An invalid digest was supplied.]]></error>
  <error id="2035"><![CDATA[RuntimeError #2035: URL Not Found.]]></error>
  <error id="3360"><![CDATA[RuntimeError #3360: Device Group registration is required before doing this operation.]]></error>
  <error id="3348"><![CDATA[RuntimeError #3348: This protected content is expired.]]></error>
  <error id="2038"><![CDATA[RuntimeError #2038: File I/O Error.]]></error>
  <error id="2039"><![CDATA[RuntimeError #2039: Invalid remote URL protocol.]]></error>
  <error id="3337"><![CDATA[RuntimeError #3337: Upgrade Flash Player or AIR  and retry playback.]]></error>
  <error id="2041"><![CDATA[RuntimeError #2041: Only one file browsing session may be performed at a time.]]></error>
  <error id="3324"><![CDATA[RuntimeError #3324: Reset license files and the client will fetch a new machine token.]]></error>
  <error id="3354"><![CDATA[RuntimeError #3354: Device Group registration is expired, please refresh the token by registering again to the DRMDeviceGroup.]]></error>
  <error id="2044"><![CDATA[RuntimeError #2044: Unhandled %1:.]]></error>
  <error id="3342"><![CDATA[RuntimeError #3342: The connected digital device doesn't have the correct capabilities.]]></error>
  <error id="2046"><![CDATA[RuntimeError #2046: The loaded file did not have a valid signature.]]></error>
  <error id="3329"><![CDATA[RuntimeError #3329: Error in application-specific namespace.]]></error>
  <error id="3330"><![CDATA[RuntimeError #3330: Need to authenticate the user and reacquire the voucher.]]></error>
  <error id="3331"><![CDATA[RuntimeError #3331: Content is not yet valid.]]></error>
  <error id="3361"><![CDATA[RuntimeError #3361: The device is not registered to this Device Group.]]></error>
  <error id="3362"><![CDATA[RuntimeError #3362: Asynchronous operation took longer than maxOperationTimeout.]]></error>
  <error id="3349"><![CDATA[RuntimeError #3349: The Flash Access server is running at a version that's higher than the max supported by this runtime.]]></error>
  <error id="2025"><![CDATA[RuntimeError #2025: The supplied DisplayObject must be a child of the caller.]]></error>
  <error id="3336"><![CDATA[RuntimeError #3336: This platform is not allowed to play this content.]]></error>
  <error id="2027"><![CDATA[RuntimeError #2027: Parameter %1 must be a non-negative number; got %2.]]></error>
  <error id="3338"><![CDATA[RuntimeError #3338: Unknown connection type.]]></error>
  <error id="3339"><![CDATA[RuntimeError #3339: Can't play back on analog device.]]></error>
  <error id="3355"><![CDATA[RuntimeError #3355: The server denied this Device Group registration request.]]></error>
  <error id="3356"><![CDATA[RuntimeError #3356: The root voucher for this content's DRMVoucher was not found.]]></error>
  <error id="3357"><![CDATA[RuntimeError #3357: The DRMContentData provides no valid embedded voucher and no Flash Access server url to acquire the voucher from.]]></error>
  <error id="3343"><![CDATA[RuntimeError #3343: Internal Error.]]></error>
  <error id="3328"><![CDATA[RuntimeError #3328: Server error; retry the request.]]></error>
  <error id="3346"><![CDATA[RuntimeError #3346: Failed migrating local DRM data, all locally cached DRM vouchers are lost.]]></error>
  <error id="3401"><![CDATA[RuntimeError #3401: Security sandbox violation: An object with this name has already been registered from another security domain.]]></error>
  <error id="3363"><![CDATA[RuntimeError #3363: The M3U8 playlist passed in had unsupported content.]]></error>
  <error id="3364"><![CDATA[RuntimeError #3364: The framework requested the device ID, but the returned value was empty.]]></error>
  <error id="3350"><![CDATA[RuntimeError #3350: The Flash Access server is running at a version that's lower than the min supported by this runtime.]]></error>
  <error id="3351"><![CDATA[RuntimeError #3351: Device Group registration token is corrupted, please refresh the token by registering again to the DRMDeviceGroup.]]></error>
  <error id="3352"><![CDATA[RuntimeError #3352: The server is using a newer version of the registration token for this Device Group.]]></error>
  <error id="3368"><![CDATA[RuntimeError #3368: The user cancelled the operation, or has entered settings that disallow access to the system.]]></error>
  <error id="3358"><![CDATA[RuntimeError #3358: ACP protection is not available on the device but required to playback the content.]]></error>
  <error id="3359"><![CDATA[RuntimeError #3359: CGMSA protection is not available on the device but required to playback the content.]]></error>
  <error id="3344"><![CDATA[RuntimeError #3344: Missing Flash Access module.]]></error>
  <error id="3365"><![CDATA[RuntimeError #3365: This browser/platform combination does not allow DRM protected playback when in incognito mode.]]></error>
  <error id="3366"><![CDATA[RuntimeError #3366: The host runtime called the Access library with a bad parameter.]]></error>
  <error id="3367"><![CDATA[RuntimeError #3367: M3U8 manifest signing failed.]]></error>
  <error id="3400"><![CDATA[RuntimeError #3400: An error occured while executing JavaScript code.]]></error>
  <error id="3402"><![CDATA[RuntimeError #3402: Security sandbox violation: Bridge caller %1 cannot access %2.]]></error>
  <error id="3500"><![CDATA[RuntimeError #3500: The extension context does not have a method with the name %1.]]></error>
  <error id="3501"><![CDATA[RuntimeError #3501: The extension context has already been disposed.]]></error>
  <error id="3502"><![CDATA[RuntimeError #3502: The extension returned an invalid value.]]></error>
  <error id="3503"><![CDATA[RuntimeError #3503: The extension was left in an invalid state.]]></error>
  <error id="2500"><![CDATA[RuntimeError #2500: An error occurred decrypting the signed swf file.]]></error>
  <error id="2501"><![CDATA[RuntimeError #2501: This property can only be accessed during screen sharing.]]></error>
  <error id="2502"><![CDATA[RuntimeError #2502: This property can only be accessed if sharing the entire screen.]]></error>
  <error id="1500"><![CDATA[RuntimeError #1500: Error opening file '%S'.]]></error>
  <error id="1501"><![CDATA[RuntimeError #1501: Error writing to file '%S'.]]></error>
  <error id="1502"><![CDATA[RuntimeError #1502: A script has executed for longer than 15 seconds.]]></error>
  <error id="1503"><![CDATA[RuntimeError #1503: A script did not exit in a timely fashion and was terminated.]]></error>
  <error id="1504"><![CDATA[RuntimeError #1504: End of file]]></error>
  <error id="1505"><![CDATA[RuntimeError #1505: The string index %d is out of bounds; must be in range %d to %d.]]></error>
  <error id="1506"><![CDATA[RuntimeError #1506: The range specified is invalid.]]></error>
  <error id="1507"><![CDATA[RuntimeError #1507: Argument '%s' may not be null.]]></error>
  <error id="1508"><![CDATA[RuntimeError #1508: The value specified for argument '%s' is invalid.]]></error>
  <error id="1509"><![CDATA[RuntimeError #1509: There was an error decompressing the data.]]></error>
  <error id="1510"><![CDATA[RuntimeError #1510: When the callback argument is a method of a class, the optional argument must be null.]]></error>
  <error id="3600"><![CDATA[RuntimeError #3600: No valid program set.]]></error>
  <error id="3601"><![CDATA[RuntimeError #3601: No valid index buffer set.]]></error>
  <error id="3602"><![CDATA[RuntimeError #3602: Sanity check on parameters failed, %1 triangles and %2 index offset.]]></error>
  <error id="3603"><![CDATA[RuntimeError #3603: Not enough indices in this buffer.]]></error>
  <error id="3604"><![CDATA[RuntimeError #3604: Sampler %1 binds a texture that is also bound for render to texture.]]></error>
  <error id="3605"><![CDATA[RuntimeError #3605: Sampler %1 binds an invalid texture.]]></error>
  <error id="3606"><![CDATA[RuntimeError #3606: Sampler %1 format does not match texture format.]]></error>
  <error id="3607"><![CDATA[RuntimeError #3607: Stream %1 is set but not used by the current vertex program.]]></error>
  <error id="3608"><![CDATA[RuntimeError #3608: Stream %1 is invalid.]]></error>
  <error id="3609"><![CDATA[RuntimeError #3609: Stream %1 does not have enough vertices.]]></error>
  <error id="3610"><![CDATA[RuntimeError #3610: Stream %1 vertex offset is out of bounds]]></error>
  <error id="3611"><![CDATA[RuntimeError #3611: Stream %1 is read by the current vertex program but not set.]]></error>
  <error id="3612"><![CDATA[RuntimeError #3612: Programs must be in little endian format.]]></error>
  <error id="3613"><![CDATA[RuntimeError #3613: The native shader compilation failed.]]></error>
  <error id="3614"><![CDATA[RuntimeError #3614: The native shader compilation failed.\nOpenGL specific: %1]]></error>
  <error id="3615"><![CDATA[RuntimeError #3615: AGAL validation failed: Program size below minimum length for %1 program.]]></error>
  <error id="3616"><![CDATA[RuntimeError #3616: AGAL validation failed: Not an AGAL program.]]></error>
  <error id="3617"><![CDATA[RuntimeError #3617: AGAL validation failed: Bad AGAL version for %1 program.]]></error>
  <error id="3618"><![CDATA[RuntimeError #3618: AGAL validation failed: Bad AGAL program type identifier for %1 program.]]></error>
  <error id="3619"><![CDATA[RuntimeError #3619: AGAL validation failed: Shader type must be either fragment or vertex for %1 program.]]></error>
  <error id="3620"><![CDATA[RuntimeError #3620: AGAL validation failed: Invalid opcode, value out of range: %2 at token %3 of %1 program.]]></error>
  <error id="3621"><![CDATA[RuntimeError #3621: AGAL validation failed: Invalid opcode, %2 is not implemented in this version at token %3 of %1 program.]]></error>
  <error id="3622"><![CDATA[RuntimeError #3622: AGAL validation failed: Opcode %2 only allowed in fragment programs at token %3 of %1 program.]]></error>
  <error id="3623"><![CDATA[RuntimeError #3623: AGAL validation failed: Block nesting underflow - EIF without opening IF condition.]]></error>
  <error id="3624"><![CDATA[RuntimeError #3624: AGAL validation failed: Block nesting overflow.]]></error>
  <error id="3625"><![CDATA[RuntimeError #3625: AGAL validation failed: Bad AGAL source operands.]]></error>
  <error id="3626"><![CDATA[RuntimeError #3626: AGAL validation failed: Opcode %2, both operands are indirect reads at token %3 of %1 program.]]></error>
  <error id="3627"><![CDATA[RuntimeError #3627: AGAL validation failed: Opcode %2 destination operand must be all zero at token %3 of %1 program.]]></error>
  <error id="3628"><![CDATA[RuntimeError #3628: AGAL validation failed: The destination operand for the %2 instruction must mask w (use .xyz or less) at token %3 of %1 program.]]></error>
  <error id="3629"><![CDATA[RuntimeError #3629: AGAL validation failed: Too many tokens (%2) for %1 program.]]></error>
  <error id="3630"><![CDATA[RuntimeError #3630: Fragment shader type is not fragment.]]></error>
  <error id="3631"><![CDATA[RuntimeError #3631: Vertex shader type is not vertex.]]></error>
  <error id="3632"><![CDATA[RuntimeError #3632: AGAL linkage: Varying %1 is read in the fragment shader but not written to by the vertex shader.]]></error>
  <error id="3633"><![CDATA[RuntimeError #3633: AGAL linkage: Varying %1 is only partially written to.]]></error>
  <error id="3634"><![CDATA[RuntimeError #3634: AGAL linkage: Fragment output needs to write to all components.]]></error>
  <error id="3635"><![CDATA[RuntimeError #3635: AGAL linkage: Vertex output needs to write to all components.]]></error>
  <error id="3636"><![CDATA[RuntimeError #3636: AGAL validation failed: Unused operand is not set to zero for %2 at token %3 of %1 program.]]></error>
  <error id="3637"><![CDATA[RuntimeError #3637: AGAL validation failed: Sampler registers only allowed in fragment programs for %2 at token %3 of %1 program.]]></error>
  <error id="3638"><![CDATA[RuntimeError #3638: AGAL validation failed: Sampler register only allowed as second operand in texture instructions for %2 at token %3 of %1 program.]]></error>
  <error id="3639"><![CDATA[RuntimeError #3639: AGAL validation failed: Indirect addressing only allowed in vertex programs for %2 at token %3 of %1 program.]]></error>
  <error id="3640"><![CDATA[RuntimeError #3640: AGAL validation failed: Indirect addressing only allowed into constant registers for %2 at token %3 of %1 program.]]></error>
  <error id="3641"><![CDATA[RuntimeError #3641: AGAL validation failed: Indirect addressing not allowed for this operand in this instruction for %2 at token %3 of %1 program.]]></error>
  <error id="3642"><![CDATA[RuntimeError #3642: AGAL validation failed: Indirect source type must be attribute, constant or temporary for %2 at token %3 of %1 program.]]></error>
  <error id="3643"><![CDATA[RuntimeError #3643: AGAL validation failed: Indirect addressing fields must be zero for direct addressing for %2 at token %3 of %1 program.]]></error>
  <error id="3644"><![CDATA[RuntimeError #3644: AGAL validation failed: Varying registers can only be read in fragment programs for %2 at token %3 of %1 program.]]></error>
  <error id="3645"><![CDATA[RuntimeError #3645: AGAL validation failed: Attribute registers can only be read in vertex programs for %2 at token %3 of %1 program.]]></error>
  <error id="3646"><![CDATA[RuntimeError #3646: AGAL validation failed: Can not read from output register for %2 at token %3 of %1 program.]]></error>
  <error id="3647"><![CDATA[RuntimeError #3647: AGAL validation failed: Temporary register read without being written to for %2 at token %3 of %1 program.]]></error>
  <error id="3648"><![CDATA[RuntimeError #3648: AGAL validation failed: Temporary register component read without being written to for %2 at token %3 of %1 program.]]></error>
  <error id="3649"><![CDATA[RuntimeError #3649: AGAL validation failed: Sampler registers can not be written to for %2 at token %3 of %1 program.]]></error>
  <error id="3650"><![CDATA[RuntimeError #3650: AGAL validation failed: Varying registers can only be written in vertex programs for %2 at token %3 of %1 program.]]></error>
  <error id="3651"><![CDATA[RuntimeError #3651: AGAL validation failed: Attribute registers can not be written to for %2 at token %3 of %1 program.]]></error>
  <error id="3652"><![CDATA[RuntimeError #3652: AGAL validation failed: Constant registers can not be written to for %2 at token %3 of %1 program.]]></error>
  <error id="3653"><![CDATA[RuntimeError #3653: AGAL validation failed: Destination writemask is zero for %2 at token %3 of %1 program.]]></error>
  <error id="3654"><![CDATA[RuntimeError #3654: AGAL validation failed: Reserve bits should be zero for %2 at token %3 of %1 program.]]></error>
  <error id="3655"><![CDATA[RuntimeError #3655: AGAL validation failed: Unknown register type for %2 at token %3 of %1 program.]]></error>
  <error id="3656"><![CDATA[RuntimeError #3656: AGAL validation failed: Sampler register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3657"><![CDATA[RuntimeError #3657: AGAL validation failed: Varying register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3658"><![CDATA[RuntimeError #3658: AGAL validation failed: Attribute register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3659"><![CDATA[RuntimeError #3659: AGAL validation failed: Constant register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3660"><![CDATA[RuntimeError #3660: AGAL validation failed: Output register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3661"><![CDATA[RuntimeError #3661: AGAL validation failed: Temporary register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3662"><![CDATA[RuntimeError #3662: AGAL validation failed: Cube map samplers must set wrapping to clamp mode for %2 at token %3 of %1 program.]]></error>
  <error id="3663"><![CDATA[RuntimeError #3663: Sampler %1 binds an undefined texture.]]></error>
  <error id="3664"><![CDATA[RuntimeError #3664: AGAL validation failed: Unknown sampler dimension %4 for %2 at token %3 of %1 program.]]></error>
  <error id="3665"><![CDATA[RuntimeError #3665: AGAL validation failed: Unknown filter mode in sampler: %4 for %2 at token %3 of %1 program.]]></error>
  <error id="3666"><![CDATA[RuntimeError #3666: AGAL validation failed: Unknown mipmap mode in sampler: %4 for %2 at token %3 of %1 program.]]></error>
  <error id="3667"><![CDATA[RuntimeError #3667: AGAL validation failed: Unknown wrapping mode in sampler: %4 for %2 at token %3 of %1 program.]]></error>
  <error id="3668"><![CDATA[RuntimeError #3668: AGAL validation failed: Unknown special flag used in sampler: %4 for %2 at token %3 of %1 program.]]></error>
  <error id="3669"><![CDATA[RuntimeError #3669: Bad input size.]]></error>
  <error id="3670"><![CDATA[RuntimeError #3670: Buffer too big.]]></error>
  <error id="3671"><![CDATA[RuntimeError #3671: Buffer has zero size.]]></error>
  <error id="3672"><![CDATA[RuntimeError #3672: Buffer creation failed.]]></error>
  <error id="3673"><![CDATA[RuntimeError #3673: Cube side must be [0..5].]]></error>
  <error id="3674"><![CDATA[RuntimeError #3674: Miplevel too large.]]></error>
  <error id="3675"><![CDATA[RuntimeError #3675: Texture format mismatch.]]></error>
  <error id="3676"><![CDATA[RuntimeError #3676: Platform does not support desired texture format.]]></error>
  <error id="3677"><![CDATA[RuntimeError #3677: Texture decoding failed.]]></error>
  <error id="3678"><![CDATA[RuntimeError #3678: Texture needs to be square.]]></error>
  <error id="3679"><![CDATA[RuntimeError #3679: Texture size does not match.]]></error>
  <error id="3680"><![CDATA[RuntimeError #3680: Depth texture not implemented yet.]]></error>
  <error id="3681"><![CDATA[RuntimeError #3681: Texture size is zero.]]></error>
  <error id="3682"><![CDATA[RuntimeError #3682: Texture size not a power of two.]]></error>
  <error id="3683"><![CDATA[RuntimeError #3683: Texture too big (max is %1x%1).]]></error>
  <error id="3684"><![CDATA[RuntimeError #3684: Texture creation failed.]]></error>
  <error id="3685"><![CDATA[RuntimeError #3685: Could not create renderer.]]></error>
  <error id="3686"><![CDATA[RuntimeError #3686: 'disabled' format only valid with a null vertex buffer.]]></error>
  <error id="3687"><![CDATA[RuntimeError #3687: Null vertex buffers require the 'disabled' format.]]></error>
  <error id="3688"><![CDATA[RuntimeError #3688: You must add an event listener for the context3DCreate event before requesting a new Context3D.]]></error>
  <error id="3689"><![CDATA[RuntimeError #3689: You can not swizzle second operand for %2 at token %3 of %1 program.]]></error>
  <error id="3690"><![CDATA[RuntimeError #3690: Too many draw calls before calling present.]]></error>
  <error id="3691"><![CDATA[RuntimeError #3691: Resource limit for this resource type exceeded.]]></error>
  <error id="3692"><![CDATA[RuntimeError #3692: All buffers need to be cleared every frame before drawing.]]></error>
  <error id="3693"><![CDATA[RuntimeError #3693: AGAL validation failed: Sampler register must be used for second operand in texture instructions for %2 at token %3 of %1 program.]]></error>
  <error id="3694"><![CDATA[RuntimeError #3694: The object was disposed by an earlier call of dispose() on it.]]></error>
  <error id="3695"><![CDATA[RuntimeError #3695: A texture can only be bound to multiple samplers if the samplers also have the exact same properties.]]></error>
  <error id="3696"><![CDATA[RuntimeError #3696: AGAL validation failed: Second use of sampler register needs to specify the exact same properties.]]></error>
  <error id="3697"><![CDATA[RuntimeError #3697: A texture is bound on sampler %1 but not used by the fragment program.]]></error>
  <error id="3698"><![CDATA[RuntimeError #3698: The back buffer is not configured.]]></error>
  <error id="3699"><![CDATA[RuntimeError #3699: Requested Operation failed to complete]]></error>
  <error id="3700"><![CDATA[RuntimeError #3700: A texture sampler binds an incomplete texture.]]></error>
  <error id="3701"><![CDATA[RuntimeError #3701: The output color register can not use a write mask.]]></error>
  <error id="3702"><![CDATA[RuntimeError #3702: Context3D not available.]]></error>
  <error id="3703"><![CDATA[RuntimeError #3703: AGAL validation failed: Source swizzle must be scalar (one of: xxxx, yyyy, zzzz, wwww) for %2 at token %3 of %1 program.]]></error>
  <error id="3704"><![CDATA[RuntimeError #3704: AGAL validation failed: Cube map samplers must enable mipmapping for %2 at token %3 of %1 program.]]></error>
  <error id="3705"><![CDATA[RuntimeError #3705: Cubemap texture too big (max is 1024x1024).]]></error>
  <error id="3706"><![CDATA[RuntimeError #3706: Scissor rectangle is set but does not intersect the framebuffer.]]></error>
  <error id="3707"><![CDATA[RuntimeError #3707: Property can not be set in non full screen mode.]]></error>
  <error id="3708"><![CDATA[RuntimeError #3708: Feature not available on this platform.]]></error>
  <error id="3709"><![CDATA[RuntimeError #3709: The depthAndStencil flag in the application descriptor must match the enableDepthAndStencil Boolean passed to configureBackBuffer on the Context3D object.]]></error>
  <error id="3710"><![CDATA[RuntimeError #3710: Requested Stage3D Operation failed to complete.]]></error>
  <error id="3711"><![CDATA[RuntimeError #3711: The streaming levels is too large.]]></error>
  <error id="3712"><![CDATA[RuntimeError #3712: Rendering to streaming textures is not allowed.]]></error>
  <error id="3713"><![CDATA[RuntimeError #3713: Incomplete streaming texture (base level not uploaded) used with no mip sampling.]]></error>
  <error id="3714"><![CDATA[RuntimeError #3714: ApplicationDomain.domainMemory is not available.]]></error>
  <error id="3715"><![CDATA[RuntimeError #3715: Too many instructions used in native shader.]]></error>
  <error id="3716"><![CDATA[RuntimeError #3716: Too many ALU instructions in native shader.]]></error>
  <error id="3717"><![CDATA[RuntimeError #3717: Too many texture instructions in native shader.]]></error>
  <error id="3718"><![CDATA[RuntimeError #3718: Too many constants used in native shader.]]></error>
  <error id="3719"><![CDATA[RuntimeError #3719: Too many temporary registers used in native shader.]]></error>
  <error id="3720"><![CDATA[RuntimeError #3720: Too many varying registers used in native shader.]]></error>
  <error id="3721"><![CDATA[RuntimeError #3721: Too many indirect texture reads in native shader.]]></error>
  <error id="3722"><![CDATA[RuntimeError #3722: Event.FRAME_LABEL event can only be registered with FrameLabel object.]]></error>
  <error id="3723"><![CDATA[RuntimeError #3723: Invalid Context3D bounds.]]></error>
  <error id="3724"><![CDATA[RuntimeError #3724: This call requires a Context3D that is created with the extended profile.]]></error>
  <error id="3725"><![CDATA[RuntimeError #3725: The requested AGAL version (%2) is not valid under the Context3D profile.]]></error>
  <error id="3726"><![CDATA[RuntimeError #3726: AGAL validation failed: Opcode %2 requires AGAL version to be at least 2, at token %3 of %1 program.]]></error>
  <error id="3727"><![CDATA[RuntimeError #3727: Failed to obtain authorization token.]]></error>
  <error id="3728"><![CDATA[RuntimeError #3728: When rendering to multiple textures slot 0 must be active.]]></error>
  <error id="3729"><![CDATA[RuntimeError #3729: When rendering to multiple textures all textures must have the same dimension and render settings.]]></error>
  <error id="3730"><![CDATA[RuntimeError #3730: When rendering to multiple textures the same texture (or cube map face) may not be bound into multiple slots.]]></error>
  <error id="3731"><![CDATA[RuntimeError #3731: This feature is not available within this context.]]></error>
  <error id="3732"><![CDATA[RuntimeError #3732: Worker.terminate is only available for background workers.]]></error>
  <error id="3735"><![CDATA[RuntimeError #3735: This API cannot accept shared ByteArrays.]]></error>
  <error id="3736"><![CDATA[RuntimeError #3736: MessageChannel is not a sender.]]></error>
  <error id="3737"><![CDATA[RuntimeError #3737: MessageChannel is not a receiver.]]></error>
  <error id="3738"><![CDATA[RuntimeError #3738: MessageChannel is closed.]]></error>
  <error id="3739"><![CDATA[RuntimeError #3739: AGAL validation failed: Open conditional block at end of %1 program.]]></error>
  <error id="3740"><![CDATA[RuntimeError #3740: AGAL validation failed: Texture samplers used in the TED instruction can not specify a lod bias.]]></error>
  <error id="3741"><![CDATA[RuntimeError #3741: AGAL validation failed: TEX instructions in an if block can not use computed texture coordinates.]]></error>
  <error id="3742"><![CDATA[RuntimeError #3742: AGAL validation failed: DDX and DDY opcodes are not allowed inside conditional blocks.]]></error>
  <error id="3743"><![CDATA[RuntimeError #3743: AGAL validation failed: The TED opcode must enable mip mapping.]]></error>
  <error id="3744"><![CDATA[RuntimeError #3744: AGAL validation failed: Color output written to multiple times.]]></error>
  <error id="3745"><![CDATA[RuntimeError #3745: Compressed texture size is too small.]]></error>
  <error id="3746"><![CDATA[RuntimeError #3746: Rendering to compressed textures is not allowed.]]></error>
  <error id="3747"><![CDATA[RuntimeError #3747: Multiple application domains are not supported on this operating system.]]></error>
  <error id="3748"><![CDATA[RuntimeError #3748: AGAL validation failed: Empty conditional branch in AGAL of %1 program.]]></error>
  <error id="3749"><![CDATA[RuntimeError #3749: AGAL validation failed: Depth output register index out of bounds for %2 at token %3 of %1 program.]]></error>
  <error id="3750"><![CDATA[RuntimeError #3750: AGAL validation failed: Depth output register is only available in fragment programs.]]></error>
  <error id="3751"><![CDATA[RuntimeError #3751: AGAL validation failed: Output registers can not be written inside conditionals.]]></error>
  <error id="3752"><![CDATA[RuntimeError #3752: AGAL validation failed: Broken else chain.]]></error>
  <error id="3753"><![CDATA[RuntimeError #3753: Rectangle or cube textures require textures sampling to be set to clamp.]]></error>
  <error id="3754"><![CDATA[RuntimeError #3754: Texture sampler dimensions mismatch.]]></error>
  <error id="3755"><![CDATA[RuntimeError #3755: Rectangle textures have to disable mip mapping and can not have a lod bias set.]]></error>
  <error id="3756"><![CDATA[RuntimeError #3756: AGAL validation failed: Depth output must set only x as a write mask.]]></error>
  <error id="3757"><![CDATA[RuntimeError #3757: AGAL validation failed: Vertex and fragment program need to have the same version.]]></error>
  <error id="3758"><![CDATA[RuntimeError #3758: AGAL validation failed: Conditional source are exactly the same, condition is constant.]]></error>
  <error id="3759"><![CDATA[RuntimeError #3759: The selected texture format is not valid in this profile.]]></error>
  <error id="3760"><![CDATA[RuntimeError #3760: The color output index is out of range.]]></error>
  <error id="3761"><![CDATA[RuntimeError #3761: The bit depth of all textures used for render to texture must be exactly the same.]]></error>
  <error id="3762"><![CDATA[RuntimeError #3762: This texture format is not supported for rectangle textures.]]></error>
  <error id="3763"><![CDATA[RuntimeError #3763: Sampler %1 binds a texture that that does not match the read mode specified in AGAL.]]></error>
  <error id="3764"><![CDATA[RuntimeError #3764: Reloading a SWF is not supported on this operating system.]]></error>
  <error id="3765"><![CDATA[RuntimeError #3765: This call requires a Context3D that is created with the baseline or baselineExtended profile.]]></error>
  <error id="3766"><![CDATA[RuntimeError #3766: RectangleTexture too big (max is the larger of %1x%1 or the size of the backbuffer).]]></error>
  <error id="3000"><![CDATA[RuntimeError #3000: Illegal path name.]]></error>
  <error id="3001"><![CDATA[RuntimeError #3001: File or directory access denied.]]></error>
  <error id="3002"><![CDATA[RuntimeError #3002: File or directory exists.]]></error>
  <error id="3003"><![CDATA[RuntimeError #3003: File or directory does not exist.]]></error>
  <error id="3004"><![CDATA[RuntimeError #3004: Insufficient file space.]]></error>
  <error id="3005"><![CDATA[RuntimeError #3005: Insufficient system resources.]]></error>
  <error id="3006"><![CDATA[RuntimeError #3006: Not a file.]]></error>
  <error id="3007"><![CDATA[RuntimeError #3007: Not a directory.]]></error>
  <error id="3008"><![CDATA[RuntimeError #3008: Read-only or write-protected media.]]></error>
  <error id="3009"><![CDATA[RuntimeError #3009: Cannot move file or directory to a different device.]]></error>
  <error id="3010"><![CDATA[RuntimeError #3010: Directory is not empty.]]></error>
  <error id="3011"><![CDATA[RuntimeError #3011: Move or copy destination already exists.]]></error>
  <error id="3012"><![CDATA[RuntimeError #3012: Cannot delete file or directory.]]></error>
  <error id="3013"><![CDATA[RuntimeError #3013: File or directory is in use.]]></error>
  <error id="3014"><![CDATA[RuntimeError #3014: Cannot copy or move a file or directory to overwrite a containing directory.]]></error>
  <error id="3015"><![CDATA[RuntimeError #3015: Loader.loadBytes() is not permitted to load content with executable code.]]></error>
  <error id="3016"><![CDATA[RuntimeError #3016: No application was found that can open this file.]]></error>
  <error id="2000"><![CDATA[RuntimeError #2000: No active security context.]]></error>
  <error id="2001"><![CDATA[RuntimeError #2001: Too few arguments were specified; got %1, %2 expected.]]></error>
  <error id="2002"><![CDATA[RuntimeError #2002: Operation attempted on invalid socket.]]></error>
  <error id="2003"><![CDATA[RuntimeError #2003: Invalid socket port number specified.]]></error>
  <error id="2005"><![CDATA[RuntimeError #2005: Parameter %1 is of the incorrect type.]]></error>
  <error id="2007"><![CDATA[RuntimeError #2007: Parameter %1 must be non-null.]]></error>
  <error id="2009"><![CDATA[RuntimeError #2009: This method cannot be used on a text field with a style sheet.]]></error>
  <error id="2010"><![CDATA[RuntimeError #2010: Local-with-filesystem SWF files are not permitted to use sockets.]]></error>
  <error id="2011"><![CDATA[RuntimeError #2011: Socket connection failed to %1:%2.]]></error>
  <error id="2013"><![CDATA[RuntimeError #2013: Feature can only be used in Flash Authoring.]]></error>
  <error id="2014"><![CDATA[RuntimeError #2014: Feature is not available at this time.]]></error>
  <error id="2015"><![CDATA[RuntimeError #2015: Invalid BitmapData.]]></error>
  <error id="2017"><![CDATA[RuntimeError #2017: Only trusted local files may cause the Flash Player to exit.]]></error>
  <error id="2018"><![CDATA[RuntimeError #2018: System.exit is only available in the standalone Flash Player.]]></error>
  <error id="2019"><![CDATA[RuntimeError #2019: Depth specified is invalid.]]></error>
  <error id="2020"><![CDATA[RuntimeError #2020: MovieClips objects with different parents cannot be swapped.]]></error>
  <error id="2021"><![CDATA[RuntimeError #2021: Object creation failed.]]></error>
  <error id="2022"><![CDATA[RuntimeError #2022: Class %1 must inherit from DisplayObject to link to a symbol.]]></error>
  <error id="2023"><![CDATA[RuntimeError #2023: Class %1 must inherit from Sprite to link to the root.]]></error>
  <error id="1000"><![CDATA[RuntimeError #1000: The system is out of memory.]]></error>
  <error id="1001"><![CDATA[RuntimeError #1001: The method %m is not implemented.]]></error>
  <error id="2026"><![CDATA[RuntimeError #2026: An error occurred navigating to the URL %1.]]></error>
  <error id="1003"><![CDATA[RuntimeError #1003: The radix argument must be between 2 and 36; got %d.]]></error>
  <error id="1004"><![CDATA[RuntimeError #1004: A method of '%t' was invoked on an incompatible object.]]></error>
  <error id="1005"><![CDATA[RuntimeError #1005: Array index is not an integer (%f).]]></error>
  <error id="1006"><![CDATA[RuntimeError #1006: Call attempted on an object that is not a function.]]></error>
  <error id="1007"><![CDATA[RuntimeError #1007: Instantiation attempted on a non-constructor.]]></error>
  <error id="2024"><![CDATA[RuntimeError #2024: An object cannot be added as a child of itself.]]></error>
  <error id="1009"><![CDATA[RuntimeError #1009: null has no properties.]]></error>
  <error id="1010"><![CDATA[RuntimeError #1010: undefined has no properties.]]></error>
  <error id="1011"><![CDATA[RuntimeError #1011: Method %m contained illegal opcode %d at offset %d.]]></error>
  <error id="1012"><![CDATA[RuntimeError #1012: The last instruction exceeded code size.]]></error>
  <error id="1013"><![CDATA[RuntimeError #1013: Cannot call OP_findproperty when scopeDepth is 0.]]></error>
  <error id="1014"><![CDATA[RuntimeError #1014: Class %n could not be found.]]></error>
  <error id="1015"><![CDATA[RuntimeError #1015: Method %m cannot set default xml namespace.]]></error>
  <error id="2032"><![CDATA[RuntimeError #2032: Stream Error.]]></error>
  <error id="1017"><![CDATA[RuntimeError #1017: Scope stack overflow.]]></error>
  <error id="1018"><![CDATA[RuntimeError #1018: Scope stack underflow.]]></error>
  <error id="1019"><![CDATA[RuntimeError #1019: Getscopeobject %d is out of bounds.]]></error>
  <error id="1020"><![CDATA[RuntimeError #1020: Code cannot fall off the end of a method.]]></error>
  <error id="1021"><![CDATA[RuntimeError #1021: At least one branch target was not on a valid instruction in the method.]]></error>
  <error id="2029"><![CDATA[RuntimeError #2029: This URLStream object does not have a stream opened.]]></error>
  <error id="1023"><![CDATA[RuntimeError #1023: Stack overflow.]]></error>
</runtimeErrors>;
       
      
      public function RuntimeErrorUtil_ERROR_DATA()
      {
         super();
      }
   }
}
